[package]
name = "iap_tool"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.2"
egui = "0.33.2"
log = "0.4.29"
probe-rs = "0.30.0"
rfd = "0.16.0"
serde = "1.0.228"
serde_json = "1.0.145"
simple_logger = "5.1.0"
